### ISSUE TITLE
Setup Questions

### ISSUE THREAD

**Issue by kennyparsons** [g0ldyy/comet#94]
I have some setup questions that I haven't been able to find much on (or I haven't understood the problem correctly). 

1. I thought this could be used without prowlarr/jacket and instead use torrentio. I enabled it in the settings but am I to just leave the indexers options empty or inspected in the UI? 

2. Does the UI need to be publicly accessible? I have it behind my zero trust network and can easily access it via the browser, but stremio errors out when trying to install, saying it's unreachable. 

```env
      - ADDON_ID=comet.stremio.techup.dev
      - ADDON_NAME=Comet
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_WORKERS=1
      - DATABASE_PATH=data/comet.db
      - CACHE_TTL=86400
      - DEBRID_PROXY_URL=http://stremio.<tsnetworkdnsname>:1080
      - GET_TORRENT_TIMEOUT=5
      - INDEXER_MANAGER_TYPE=none
      - INDEXER_MANAGER_API_KEY=none
      - ZILEAN_URL=None
      - ZILEAN_TAKE_FIRST=500
      - SCRAPE_TORRENTIO=True
      - CUSTOM_HEADER_HTML=None
      - PROXY_DEBRID_STREAM=True
      - PROXY_DEBRID_STREAM_PASSWORD=redacted
      - TITLE_MATCH_CHECK=True

```

**Comment by g0ldyy** [comment]
1) just set jackett and a random password in config

2) yes it needs to be accessible publicly. to check if it's working, try opening it in your browser private window

**Comment by utkarshsethi** [comment]
@g0ldyy does the password in config have to be in ""? as the stream seems to work even if I did not enter a password in the UI

**Comment by kennyparsons** [comment]
So I did some digging:
1. In the web version of stremio, I opened the dev console and saw the install addon failed because the site was http, not https. I configured nginx with valid tailscale public certs, accessible only on the tailscale network. I can now install the addon. But a new problem emerges:
2. When i start a stream, I get video but no audio. So I investigate further:

I open the dev console and again see an http block message after starting the video:
![image](https://github.com/user-attachments/assets/e776c158-d8f0-4253-a4c9-ab674ae476d9)

Comet is only being served over nginx/https, yet something is calling for http. To be sure, I put in an http-->https redirect for all calls, but the browser is just blocking it, and letting it redirect to https.

**Comment by Zaarrg** [comment]
So about the audio problem:
- Had the same problem with no audio. It was caused for me atleast because stremio web did not connect to the stremio-server correctly, showed up in the web ui settings of stremio as offline.

- Also depending on the stream the browser might not support it and cause the no audio issue. 
- And not sure if related to the audio issue but i fixed the stremio-server issue by using v5 of stremio which supports transcoding and had no problems since. You can find a list of what version supports what [here](https://elfhosted.com/app/stremio-server/#client-compatibility)

Limited Accessibility:
- What I did to make it not publicly available is to set up stremio-web, stremio-server and comet behind a ip whitelist.

**Comment by g0ldyy** [comment]
web audio is broken on Stremio for most content, it's not a Comet issue.
try with very small content like less than 1gb and you will have audio
